[providers]
python = "3.11"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmd = "python3.11 -m pip install -r requirements.txt"

[phases.build]
cmd = "echo 'Build complete'"

[start]
cmd = "python3.11 app.py"
